version: 0.0.{build}
branches:
  only:
  - master
init:
- ps: git config --global core.autocrlf true
install:
- ps: >-
    Write-Host "PowerShell Version:" $PSVersionTable.PSVersion.tostring()

    Install-PackageProvider -Name NuGet -MinimumVersion 2.8.5.201 -Force

    Install-Module Pester, PSFramework, PSModuleDevelopment, PSUtil, PSScriptAnalyzer, InvokeBuild -Force
build_script:
- ps: >-
    $ErrorActionPreference = 'Stop'

    #Update-Help # we need up-to-date help content for tests

    cd .\ScienceLogic_SL1

    Invoke-Build
test_script:
- ps: >-
    cd tests

    .\pester.ps1
artifacts:
- path: ScienceLogic_SL1/Artifacts
  name: ScienceLogic_SL1